import { useRef, useState } from "react";
import { useApp } from "../state/AppState";
import { exchangeInstruments, money, useExchangeQuotes } from "../lib/exchangeQuotes";
import "./ConnectedScreens.css";

function defaultExpiry() { const date = new Date(); date.setMonth(date.getMonth() + 1); return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}T23:55`; }
function formatExpiry(value: string) { return new Date(value).toLocaleString("ru-RU", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit" }); }
function AccountCard({ balance }: { balance: number }) { return <div className="order-account"><span className="order-account-icon">▣</span><div><strong>Брокерский счет</strong><span>Основной · демо</span></div><strong>{money(balance)}</strong></div>; }

export function ExchangeOrder() {
  const app = useApp(); const params = app.current.params ?? {}; const quotes = useExchangeQuotes();
  const item = exchangeInstruments.find(item => item.id === params.id);
  const [side, setSide] = useState(params.side ?? "buy");
  const [quantity, setQuantity] = useState(params.quantity ? String(params.quantity) : "");
  const [price, setPrice] = useState(String(params.orderPrice ?? quotes[params.id ?? ""]?.price ?? ""));
  const [type, setType] = useState<"limit" | "market">(params.orderType ?? "limit");
  const [sizing, setSizing] = useState<"quantity" | "amount">("quantity");
  const [amount, setAmount] = useState("");
  const [expires, setExpires] = useState(params.expires ?? defaultExpiry());
  if (!item) return <div className="order-screen"><button onClick={app.back}>Назад</button><p>Инструмент не найден</p></div>;
  const selectedPrice = type === "market" ? quotes[item.id].price : Number(price.replace(",", "."));
  const count = sizing === "quantity" ? Number(quantity) : Math.floor(Number(amount.replace(",", ".")) / selectedPrice);
  const valid = Number.isSafeInteger(count) && count > 0 && count <= 1000000 && Number.isFinite(selectedPrice) && selectedPrice > 0 && Number.isFinite(count * selectedPrice) && (type === "market" || new Date(expires).getTime() > Date.now());
  const total = valid ? count * selectedPrice : 0;
  function proceed() { if (!valid) return; const draft = { id: item!.id, source: "exchange" as const, side, quantity: count, orderPrice: selectedPrice, orderType: type, expires }; app.replace("trade", draft); app.go("trade-confirmation", draft); }
  return <section className="order-screen"><header className="connected-header"><button aria-label="Назад к инструменту" onClick={app.back}>←</button><div><h1>{item.title}</h1><span className="order-live">{money(quotes[item.id].price, item.decimals)} · Демо</span></div></header><div className="order-segment">{(["buy", "sell"] as const).map(value => <button key={value} aria-pressed={side === value} onClick={() => setSide(value)}>{value === "buy" ? "Купить" : "Продать"}</button>)}</div><AccountCard balance={app.account.cash}/><div className="order-options"><select aria-label="Тип заявки" value={type} onChange={event => setType(event.target.value as "limit" | "market")}><option value="limit">Лимитная</option><option value="market">Рыночная</option></select><div>{(["quantity", "amount"] as const).map(value => <button key={value} aria-pressed={sizing === value} onClick={() => { if (value === "quantity" && Number.isFinite(count) && count > 0) setQuantity(String(count)); if (value === "amount" && total > 0) setAmount(total.toFixed(2)); setSizing(value); }}>{value === "quantity" ? "Количество" : "На сумму"}</button>)}</div></div><div className="order-field"><label htmlFor="order-quantity">{sizing === "quantity" ? `Количество (${item.currency ? "единиц валюты" : "акций"})` : "Сумма, ₽"}</label><div><input id="order-quantity" inputMode={sizing === "quantity" ? "numeric" : "decimal"} placeholder={sizing === "quantity" ? "от 1" : "Введите сумму"} value={sizing === "quantity" ? quantity : amount} onChange={event => { const value = event.target.value; if (sizing === "quantity" && /^\d{0,7}$/.test(value)) setQuantity(value); if (sizing === "amount" && /^\d{0,12}([.,]\d{0,2})?$/.test(value)) setAmount(value); }}/>{sizing === "quantity" && <><button aria-label="Уменьшить количество" onClick={() => setQuantity(String(Math.max(0, (Number(quantity) || 0) - 1)))}>−</button><button aria-label="Увеличить количество" onClick={() => setQuantity(String(Math.min(1000000, (Number(quantity) || 0) + 1)))}>+</button></>}</div></div><div className="order-field"><label htmlFor="order-price">Цена за {item.currency ? "единицу" : "акцию"}, ₽</label><input id="order-price" inputMode="decimal" value={type === "market" ? String(quotes[item.id].price) : price} disabled={type === "market"} onChange={event => { if (/^\d{0,10}([.,]\d{0,4})?$/.test(event.target.value)) setPrice(event.target.value); }}/></div>{type === "limit" && <label className="order-expiry">Заявка действует до<input aria-label="Срок действия заявки" type="datetime-local" value={expires} onChange={event => setExpires(event.target.value)}/></label>}<div className="order-total"><span>{valid ? `${count} ${item.currency ? "ед." : "шт."}` : "Сумма заявки"}</span><strong>{money(total)}</strong></div><p className="order-info">ⓘ Демо-заявка. Деньги и ценные бумаги не списываются.</p><button className="connected-primary" disabled={!valid} onClick={proceed}>{side === "buy" ? "Купить" : "Продать"}</button></section>;
}

export function TradeConfirmation() {
  const app = useApp(); const params = app.current.params ?? {}; const item = exchangeInstruments.find(item => item.id === params.id); const [done, setDone] = useState(false); const submitted = useRef(false);
  const quantity = params.quantity ?? 0; const price = params.orderPrice ?? 0; const total = quantity * price;
  if (!item || !Number.isSafeInteger(quantity) || quantity <= 0 || !Number.isFinite(price) || price <= 0) return <section className="order-screen"><button onClick={app.back}>Назад</button><p>Нет данных заявки</p></section>;
  return <section className="order-screen order-confirmation"><header className="connected-header"><button aria-label="Назад к заявке" onClick={app.back}>←</button><div><h1>{done ? "Заявка подтверждена" : params.side === "sell" ? "Продажа" : "Покупка"}</h1></div></header><h2>Актив</h2><div className="order-asset"><img src={item.image} width={36} height={36} alt=""/><div><strong>{item.title}</strong><span>{item.id}</span></div><div><strong data-testid="confirmation-total">{money(total)}</strong><span>{quantity} {item.currency ? "ед." : "шт."} · {money(price, item.decimals)}</span></div></div><div className="order-validity"><span>{params.orderType === "market" ? "Тип заявки" : "Заявка действует до"}</span><strong>{params.orderType === "market" ? "Рыночная" : formatExpiry(params.expires ?? defaultExpiry())}</strong></div><p className="order-info">ⓘ {done ? "Демо-заявка подтверждена. На биржу не отправлена." : "Проверьте данные демо-заявки. Реальные операции не совершаются."}</p><h2>Счет</h2><AccountCard balance={app.account.cash}/><div className="order-confirm-action"><button className="connected-primary" onClick={() => { if (done) { app.tab("portfolio"); return; } if (!submitted.current) { submitted.current = true; setDone(true); } }}>{done ? "Вернуться на Биржу" : "Подтвердить"}</button></div></section>;
}
