import { useState } from "react";
import { useApp } from "../state/AppState";
import "./Reports.css";

const reportTitles = ["Брокерский отчет", "Выписка по счету депо", "Отчет о выплатах по ценным бумагам", "Справка о стоимости выводимых ценных бумаг", "Справка 2-НДФЛ", "Сводный налоговый отчет", "Копия брокерского соглашения", "Извещение об открытии счета"];
const types = ["День", "Месяц", "Год", "Свой период"];
function today() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; }
function downloadDemo(title: string, period: string) {
  const url = URL.createObjectURL(new Blob([`ДЕМОНСТРАЦИОННЫЙ ДОКУМЕНТ\n${title}\n${period}\n\nСоздан в прототипе. Не является банковским документом.`], { type: "text/plain;charset=utf-8" }));
  const link = document.createElement("a"); link.href = url; link.download = `${title.replace(/[^а-яА-Яa-zA-Z0-9 -]/g, "")}-демо.txt`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}
export function Reports({ ready = false }: { ready?: boolean }) {
  const app = useApp(); const [tab, setTab] = useState(ready ? 1 : 0);
  return <section className="reports-screen"><header className="reports-header"><button aria-label="Назад" onClick={app.back}>←</button><h1>Отчеты и справки</h1></header><div className="reports-tabs" data-tour="reports-tabs" role="tablist" aria-label="Отчеты">{["Заказать", "Скачать готовые"].map((title, index) => <button key={title} role="tab" aria-selected={tab === index} onClick={() => setTab(index)}>{title}</button>)}</div>{tab === 0 ? <div>{reportTitles.map((title, index) => <button className="reports-row" key={title} onClick={() => app.go("doc-order", { id: String(index) })}><span>{title}</span><span aria-hidden="true">›</span></button>)}</div> : <div className="reports-ready"><p>Готовые документы хранятся 7 дней: сохраните их на свое устройство, чтобы пользоваться позднее. Заказать документы снова можно в любое время.</p>{app.account.docs.filter(doc => Date.now() - doc.ts < 7 * 86400000).map(doc => <button className="reports-row" key={doc.id} disabled={doc.status !== "ready"} onClick={() => downloadDemo(doc.title, doc.period)}><span>{doc.title}<small>{doc.period}<br/>{doc.status === "ready" ? "Скачать демо-файл (.txt)" : "Формируется…"}</small></span><span aria-hidden="true">↓</span></button>)}{app.account.docs.filter(doc => Date.now() - doc.ts < 7 * 86400000).length === 0 && <div className="reports-empty">Пока нет готовых документов<button onClick={() => setTab(0)}>Заказать документ</button></div>}</div>}</section>;
}
export function BrokerReport() {
  const app = useApp(); const title = reportTitles[Number(app.current.params?.id ?? 0)] ?? reportTitles[0];
  const [account, setAccount] = useState("11MD3A/1CY8P"); const [type, setType] = useState("День"); const [start, setStart] = useState(""); const [end, setEnd] = useState(""); const [ordered, setOrdered] = useState(false);
  const max = today();
  const validStart = type === "Год" ? /^\d{4}$/.test(start) && Number(start) >= 2000 && Number(start) <= Number(max.slice(0,4)) : type === "Месяц" ? /^\d{4}-\d{2}$/.test(start) && start <= max.slice(0,7) : /^\d{4}-\d{2}-\d{2}$/.test(start) && start <= max;
  const valid = validStart && (type !== "Свой период" || Boolean(end && end >= start && end <= max));
  function order(format: string) { if (!valid || ordered) return; app.orderDoc(`${title} (${format})`, `${account} · ${type === "Свой период" ? `${start} — ${end}` : start}`); setOrdered(true); }
  return <section className="reports-screen"><header className="reports-header"><button aria-label="Назад к отчетам" onClick={app.back}>←</button><h1>{title}</h1></header>{ordered ? <div className="reports-success"><span>✓</span><h2>Документ заказан</h2><p>Демо-документ появится в готовых через несколько секунд.</p><button onClick={() => app.replace("doc-ready")}>Скачать готовые</button></div> : <><label className="reports-account"><span aria-hidden="true">▣</span><div>Брокерский {account.includes("/") ? "субсчет" : "счет"}<select aria-label="Брокерский счет" value={account} onChange={event => setAccount(event.target.value)}><option value="11MD3A/1CY8P">11MD3A/1CY8P</option><option value="11MD3A">11MD3A · Основной</option></select></div></label><h2>Тип периода</h2><div className="reports-period-types">{types.map(value => <button key={value} aria-pressed={type === value} onClick={() => { setType(value); setStart(""); setEnd(""); }}>{value}</button>)}</div><div className="reports-period"><label>{type === "Свой период" ? "Начало периода" : "Период"}<input aria-label={type === "Свой период" ? "Начало периода" : "Период"} type={type === "Год" ? "number" : type === "Месяц" ? "month" : "date"} min={type === "Год" ? "2000" : undefined} max={type === "Год" ? max.slice(0,4) : type === "Месяц" ? max.slice(0,7) : max} value={start} onChange={event => setStart(event.target.value)}/></label>{type === "Свой период" && <label>Конец периода<input aria-label="Конец периода" type="date" min={start} max={max} value={end} onChange={event => setEnd(event.target.value)}/></label>}</div><p className="reports-hint">Отчет за предыдущий день можно заказать сегодня после 12:00 мск.</p><p className="reports-hint">Брокерский отчет формируется сразу по всем площадкам: основной, внебиржевой и срочный рынок.</p><div className="reports-submit"><button disabled={!valid} onClick={() => order("xls")}>Заказать в xls</button><button disabled={!valid} onClick={() => order("pdf")}>Заказать в pdf</button></div></>}</section>;
}
