import { lessonAssets } from '../../lib/lessonAssets';
import { quizAssets } from '../../lib/quizAssets';
import { quizQuestions } from '../../lib/quiz1';

export function QuizRobot({ pose }: { pose: keyof typeof quizAssets }) { return <div className={`quiz-art quiz-art-${pose}`}><img src={quizAssets[pose]} alt="ФинКод" width={320} height={300} decoding="async"/>{pose === 'success' && <div className="quiz-confetti" aria-hidden="true">{Array.from({length:12},(_,i)=><i key={i} style={{left:`${8+i*7.5}%`,top:`${5+(i%4)*17}%`,transform:`rotate(${i*37}deg)`}}/>)}</div>}</div>; }
export function AnswerOption({ label, selected, disabled, onClick }: { label: string; selected: boolean; disabled: boolean; onClick: () => void }) { return <button type="button" role="radio" aria-checked={selected} disabled={disabled} className={`quiz-option${selected?' selected':''}`} onClick={onClick}><span aria-hidden="true">{selected?'✓':''}</span><span>{label}</span></button>; }
export function QuizReward({ amount }: { amount: number }) { return <div className="quiz-reward"><img src={lessonAssets.coin} alt="" width={54} height={54}/><div><strong>+{amount}</strong><span>финкоинов</span></div></div>; }
export function ExplanationCard({ question }: { question: typeof quizQuestions[number] }) { return <><div className="quiz-correct"><span aria-hidden="true">✓</span><p><small>Правильный ответ:</small>{question.answers[question.correctAnswer]}</p></div><div className="quiz-explanation"><img src={lessonAssets.bulb} alt="" width={38} height={48}/><p>{question.explanation}</p></div></>; }
export function CheckingIndicator() { return <div className="quiz-checking-dots" role="status" aria-label="Проверяем ответы">{[0,1,2,3,4].map(i=><i key={i} style={{animationDelay:`${i*.18}s`}}/>)}</div>; }
export function ResultStats({ seconds, score, coins }: { seconds: number; score: number; coins: number }) { return <div className="quiz-stats"><div><span className="quiz-stat-icon">◷</span><strong>{seconds < 60 ? `${seconds} сек` : `${Math.floor(seconds/60)} мин ${seconds%60} с`}</strong><small>время</small></div><div><span className="quiz-stat-check">✓</span><strong>{score}%</strong><small>результат</small></div><div><img src={lessonAssets.coin} alt="" width={34} height={34}/><strong>+{coins}</strong><small>финкоинов</small></div></div>; }
