// Demonstration content from the supplied HTML snapshot; never live market data.
export const placements = [
  {
    title: "Атомэнпр18 (расч. в CNY)",
    type: "Облигации",
    term: "На 1 год 6 мес.",
    value: "Купон: 8.5-8.75% в ¥",
  },
  {
    title: "Атомэнпр18 (расч. в RUB)",
    type: "Облигации",
    term: "На 1 год 6 мес.",
    value: "Купон: 8.5-8.75% в ¥",
  },
  {
    title: "СО ВТБ С-1-1722 «Умножение капитала+»",
    type: "Облигации",
    term: "На 5 лет",
    value: "Купон: 16.76% в ₽*",
  },
  {
    title: "ЗПИФН ВИМ РД 3",
    type: "Фонды",
    term: "SFO",
    value: "Цена: 1 046,86 ₽",
  },
  {
    title: "ЗПИКФ ВИМ - Спектр",
    type: "Фонды",
    term: "SFO",
    value: "Цена: 106 852,99 ₽",
  },
  {
    title: "ЗПИФ «РД 2»",
    type: "Фонды",
    term: "SFO",
    value: "Цена: 134 152,81 ₽",
  },
  {
    title: "РКСОлмA902",
    type: "Облигации",
    term: "На 6 лет 9 мес.",
    value: "Купон: до 15% в ₽",
  },
  {
    title: "ВТБ Б-1-420 «Сохранность»",
    type: "Облигации",
    term: "На 1 год",
    value: "Купон: 13.7% в ₽",
  },
  {
    title: "ВТБ Б1-400",
    type: "Облигации",
    term: "На 92 дня",
    value: "Купон: 13.5% в ₽",
  },
  {
    title: "СФО ТБ-11",
    type: "Облигации",
    term: "1 год 11 мес.*",
    value: "Купон: 16.5% в ₽",
  },
  {
    title: "ЛОЭСК 1Р1",
    type: "Облигации",
    term: "На 3 года",
    value: "Купон: 18.5% в ₽",
  },
  {
    title: "АСВ 1Р06",
    type: "Облигации",
    term: "На 3 года",
    value: "Купон: 24% в ₽",
  },
  {
    title: "ДелПорт1P5 (Доп выпуск)",
    type: "Облигации",
    term: "На 2 года 10 мес.",
    value: "Купон: 17.05% в ₽",
  },
  {
    title: "НоваБев3Р4",
    type: "Облигации",
    term: "На 3 года",
    value: "Купон: 16.5% в ₽",
  },
  {
    title: "НоваБев3Р5",
    type: "Облигации",
    term: "На 2 года",
    value: "Купон: Около 16,5%",
  },
  {
    title: "РУСАЛ 1Р17 (расч. в RUB)",
    type: "Облигации",
    term: "На 2 года",
    value: "Купон: Ожидается",
  },
  {
    title: "РУСАЛ 1Р17 (расч. в CNY)",
    type: "Облигации",
    term: "На 2 года",
    value: "Купон: Ожидается",
  },
  {
    title: "ЯТЭК 1P-7",
    type: "Облигации",
    term: "На 2 года 6 мес.",
    value: "Купон: Около 17,5%",
  },
  {
    title: "ОТЭКО 1Р1",
    type: "Облигации",
    term: "На 2 года",
    value: "Купон: 18.5% в ₽",
  },
  {
    title: "NSKATD1Р01",
    type: "Облигации",
    term: "На 1 год 10 мес.",
    value: "Купон: до 21.5% в ₽",
  },
  {
    title: "iВУШ 1P8",
    type: "Облигации",
    term: "На 3 года",
    value: "Купон: до 22% в ₽",
  },
  {
    title: "АЛЬЯНС 1P9",
    type: "Облигации",
    term: "На 2 года 5 мес.",
    value: "Купон: до 23.51% в ₽",
  },
  {
    title: "БЭЛТИ БОП9",
    type: "Облигации",
    term: "На 3 года 3 мес.",
    value: "Купон: до 19% в ₽",
  },
  {
    title: "Бустер Б04",
    type: "Облигации",
    term: "На 2 года 11 мес.",
    value: "Купон: до 22.5% в ₽",
  },
  {
    title: "ВОСТКОЙЛ-2",
    type: "Облигации",
    term: "На 4 года 5 мес.",
    value: "Купон: до 26% в ₽",
  },
  {
    title: "Вернём1Р4",
    type: "Облигации",
    term: "На 2 года 11 мес.",
    value: "Купон: до 25.5% в ₽",
  },
  {
    title: "ГрупПроБ03",
    type: "Облигации",
    term: "На 2 года 6 мес.",
    value: "Купон: до 23% в ₽",
  },
  {
    title: "ЗО-001P-01",
    type: "Облигации",
    term: "На 2 года 11 мес.",
    value: "Купон: до 25.5% в ₽",
  },
  {
    title: "ИНТРФУД-02",
    type: "Облигации",
    term: "На 2 года 11 мес.",
    value: "Купон: до 28% в ₽",
  },
  {
    title: "КДСНН01",
    type: "Облигации",
    term: "На 3 года 11 мес.",
    value: "Купон: до 24% в ₽",
  },
  {
    title: "Кеарли 1Р2",
    type: "Облигации",
    term: "На 2 года 7 мес.",
    value: "Купон: до 25% в ₽",
  },
  {
    title: "МеталТрБ01",
    type: "Облигации",
    term: "На 3 года 9 мес.",
    value: "Купон: до 25.5% в ₽",
  },
  {
    title: "ПионЛизБО9",
    type: "Облигации",
    term: "На 4 года 7 мес.",
    value: "Купон: до 26.5% в ₽",
  },
  {
    title: "РКС2Р9",
    type: "Облигации",
    term: "На 2 года 11 мес.",
    value: "Купон: до 24% в ₽",
  },
  {
    title: "РУССОЙЛ-02",
    type: "Облигации",
    term: "На 2 года 10 мес.",
    value: "Купон: до 22.25% в ₽",
  },
  {
    title: "СБСекр6АС",
    type: "Облигации",
    term: "На 9 лет",
    value: "Купон: 16%",
  },
  {
    title: "СЗА БО-08",
    type: "Облигации",
    term: "На 2 года 11 мес.",
    value: "Купон: до 25% в ₽",
  },
  {
    title: "СКСЛомбБ03",
    type: "Облигации",
    term: "На 2 года 8 мес.",
    value: "Купон: до 21.5% в ₽",
  },
  {
    title: "СибСтекБ04",
    type: "Облигации",
    term: "На 2 года 8 мес.",
    value: "Купон: до 25.5% в ₽",
  },
  {
    title: "Сульфур1P2",
    type: "Облигации",
    term: "На 3 года 1 мес.",
    value: "Купон: до 28% в ₽",
  },
  {
    title: "ТАЛК002P04",
    type: "Облигации",
    term: "На 3 года 3 мес.",
    value: "Купон: до 24% в ₽",
  },
  {
    title: "ЗПИКФ Место Встречи",
    type: "Фонды",
    term: "DPO",
    value: "Цена: 900 ₽",
  },
  {
    title: "ТАЛК003P01",
    type: "Облигации",
    term: "На 3 года 9 мес.",
    value: "Купон: до 21.3% в ₽",
  },
  {
    title: "Петрокартон",
    type: "Акции",
    term: "Pre-IPO",
    value: "Цена: 7,55 ₽",
  },
  {
    title: "ТЕХНЛГ 04",
    type: "Облигации",
    term: "На 2 года 10 мес.",
    value: "Купон: до 22.75% в ₽",
  },
  {
    title: "ТатнхимP03",
    type: "Облигации",
    term: "На 4 года 10 мес.",
    value: "Купон: до 20.5% в ₽",
  },
  {
    title: "УПТК65 1P2",
    type: "Облигации",
    term: "На 4 года 5 мес.",
    value: "Купон: до 22% в ₽",
  },
  {
    title: "ЭЛРЕШ 1Р4",
    type: "Облигации",
    term: "На 1 год 10 мес.",
    value: "Купон: до 22% в ₽",
  },
  {
    title: "ЭлАп БО-04",
    type: "Облигации",
    term: "На 4 года 8 мес.",
    value: "Купон: до 17.5% в ₽",
  },
  {
    title: "ЮУЛЦ 1Р3",
    type: "Облигации",
    term: "На 2 года 10 мес.",
    value: "Купон: до 23.51% в ₽",
  },
] as const;
export const ideas = [
  {
    title: "ВИМ - Золото (GOLD)",
    type: "Фонды",
    action: "Покупать",
    potential: "+ 10,8%",
    price: "3,3 ₽",
    remaining: "5 мес. 21дн.",
    date: "Дата открытия идеи 17 сентября 2026",
  },
  {
    title: "Мечел",
    type: "Акции • Черная металлургия",
    action: "Покупать",
    potential: "+ 34,1%",
    price: "55 ₽",
    remaining: "2 мес. 17дн.",
    date: "Дата открытия идеи 11 сентября 2026",
  },
  {
    title: "Озон Фармацевтика",
    type: "Акции • Медицина",
    action: "Покупать",
    potential: "+ 10,4%",
    price: "49 ₽",
    remaining: "2 мес. 9дн.",
    date: "Дата открытия идеи 3 сентября 2026",
  },
  {
    title: "Сургутнефтегаз-п",
    type: "Акции • Нефть и газ",
    action: "Покупать",
    potential: "+ 11,3%",
    price: "45 ₽",
    remaining: "1 мес. 14дн.",
    date: "Дата открытия идеи 29 июля 2026",
  },
  {
    title: "Транснефть-п",
    type: "Акции • Нефть и газ",
    action: "Покупать",
    potential: "+ 22,7%",
    price: "1 250 ₽",
    remaining: "24дн.",
    date: "Дата открытия идеи 9 июля 2026",
  },
  {
    title: "Банк «Санкт-Петербург»",
    type: "Акции • Банки",
    action: "Покупать",
    potential: "+ 27,3%",
    price: "330 ₽",
    remaining: "3 мес.",
    date: "Дата открытия идеи 26 июня 2026",
  },
  {
    title: "Газпром",
    type: "Акции • Нефть и газ",
    action: "Покупать",
    potential: "+ 28,1%",
    price: "130 ₽",
    remaining: "2 мес. 27дн.",
    date: "Дата открытия идеи 23 июня 2026",
  },
  {
    title: "Фосагро",
    type: "Акции • Химия",
    action: "Покупать",
    potential: "+ 45,1%",
    price: "7 500 ₽",
    remaining: "2 мес. 13дн.",
    date: "Дата открытия идеи 9 июня 2026",
  },
  {
    title: "Циан",
    type: "Акции",
    action: "Покупать",
    potential: "+ 7%",
    price: "700 ₽",
    remaining: "2 мес. 8дн.",
    date: "Дата открытия идеи 4 июня 2026",
  },
  {
    title: "Газпром нефть",
    type: "Акции • Нефть и газ",
    action: "Покупать",
    potential: "+ 6,9%",
    price: "590 ₽",
    remaining: "1 мес. 30дн.",
    date: "Дата открытия идеи 26 мая 2026",
  },
  {
    title: "Хэдхантер",
    type: "Акции • Технологии",
    action: "Покупать",
    potential: "+ 18,4%",
    price: "3 400 ₽",
    remaining: "1 мес. 24дн.",
    date: "Дата открытия идеи 20 мая 2026",
  },
  {
    title: "Новатэк",
    type: "Акции • Нефть и газ",
    action: "Покупать",
    potential: "+ 29,4%",
    price: "1 390 ₽",
    remaining: "27дн.",
    date: "Дата открытия идеи 23 апреля 2026",
  },
  {
    title: "Русал",
    type: "Акции • Цветная металлургия",
    action: "Покупать",
    potential: "+ 144,9%",
    price: "60 ₽",
    remaining: "21дн.",
    date: "Дата открытия идеи 17 апреля 2026",
  },
  {
    title: "БАЗИС",
    type: "Акции • Технологии",
    action: "Покупать",
    potential: "+ 25,1%",
    price: "133 ₽",
    remaining: "1 мес. 6дн.",
    date: "Дата открытия идеи 2 апреля 2026",
  },
  {
    title: "КЦ ИКС 5",
    type: "Акции • Торговля",
    action: "Покупать",
    potential: "+ 36,5%",
    price: "2 500 ₽",
    remaining: "2 мес. 19дн.",
    date: "Дата открытия идеи 17 марта 2026",
  },
  {
    title: "Московская биржа",
    type: "Акции • Финансы",
    action: "Покупать",
    potential: "+ 20,7%",
    price: "180 ₽",
    remaining: "1 мес. 16дн.",
    date: "Дата открытия идеи 11 февраля 2026",
  },
  {
    title: "Яндекс",
    type: "Акции • Технологии",
    action: "Покупать",
    potential: "+ 56,9%",
    price: "5 900 ₽",
    remaining: "27дн.",
    date: "Дата открытия идеи 23 января 2026",
  },
  {
    title: "ВИМ - Индекс Мосбиржи",
    type: "Фонды",
    action: "Покупать",
    potential: "+ 29,1%",
    price: "163,7 ₽",
    remaining: "2дн.",
    date: "Дата открытия идеи 29 декабря 2025",
  },
  {
    title: "Ростелеком",
    type: "Акции • Связь",
    action: "Покупать",
    potential: "+ 92,8%",
    price: "77 ₽",
    remaining: "2 мес. 17дн.",
    date: "Дата открытия идеи 15 декабря 2025",
  },
  {
    title: "Позитив",
    type: "Акции • Технологии",
    action: "Покупать",
    potential: "+ 25,1%",
    price: "1 320 ₽",
    remaining: "1 мес. 3дн.",
    date: "Дата открытия идеи 31 октября 2025",
  },
  {
    title: "Интер РАО ЕЭС",
    type: "Акции • Энергетика",
    action: "Покупать",
    potential: "+ 74,6%",
    price: "4,2 ₽",
    remaining: "1 мес. 14дн.",
    date: "Дата открытия идеи 13 августа 2025",
  },
] as const;

export const placementLogos = [
  "asset-006.png",
  "asset-006.png",
  "asset-092.png",
  "asset-201.png",
  "asset-201.png",
  "asset-201.png",
  "asset-092.png",
  "asset-092.png",
  "asset-092.png",
  "asset-094.png",
  "asset-096.png",
  "asset-098.png",
  "asset-100.png",
  "asset-010.png",
  "asset-010.png",
  "asset-012.png",
  "asset-012.png",
  "asset-102.png",
  "asset-104.png",
  "asset-106.png",
  "asset-108.png",
  "asset-110.png",
  "asset-112.png",
  "asset-114.png",
  "asset-116.png",
  "asset-118.png",
  "asset-120.png",
  "asset-122.png",
  "asset-124.png",
  "asset-126.png",
  "asset-128.png",
  "asset-130.png",
  "asset-132.png",
  "asset-134.png",
  "asset-136.png",
  "asset-018.png",
  "asset-138.png",
  "asset-140.png",
  "asset-142.png",
  "asset-144.png",
  "asset-020.png",
  "asset-146.png",
  "asset-020.png",
  "asset-148.png",
  "asset-150.png",
  "asset-152.png",
  "asset-154.png",
  "asset-156.png",
  "asset-158.png",
  "asset-160.png",
];
export const ideaLogos = [
  "asset-201.png",
  "asset-172.png",
  "asset-174.png",
  "asset-022.png",
  "asset-176.png",
  "asset-178.png",
  "asset-026.png",
  "asset-180.png",
  "asset-032.png",
  "asset-182.png",
  "asset-034.png",
  "asset-024.png",
  "asset-012.png",
  "asset-184.png",
  "asset-036.png",
  "asset-038.png",
  "asset-028.png",
  "asset-201.png",
  "asset-188.png",
  "asset-190.png",
  "asset-040.png",
];
